global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'rest-service'
    static_configs:
      - targets: ['rest-service:8081']

  - job_name: 'grpc-service'
    static_configs:
      - targets: ['grpc-service:8082']

  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8083']
  
  - job_name: "windows-exporter"
    static_configs:
      - targets: ["host.docker.internal:9182"]
